name: Labels

on:
  push:
    branches:
      - master
    paths:
      - '.github/labels.json'

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: "Update Issue Labels"
      uses: lannonbr/issue-label-manager-action@2.0.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
